# Generated by Django 6.0.2 on 2026-02-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_no', models.CharField(max_length=64, unique=True)),
                ('receipt_date', models.DateField()),
                ('invoice_no', models.CharField(blank=True, default='', max_length=64)),
                ('supplier', models.CharField(blank=True, default='', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='Open', max_length=32)),
            ],
            options={
                'db_table': 'goods_receipts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('cost_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('stock_qty', models.IntegerField()),
                ('reorder_qty', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=64)),
                ('invoice_date', models.DateField()),
                ('supplier', models.CharField(max_length=128)),
                ('total_amount', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'purchase_invoices',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_no', models.CharField(max_length=64, unique=True)),
                ('po_no', models.CharField(blank=True, default='', max_length=64)),
                ('gr_no', models.CharField(blank=True, default='', max_length=64)),
                ('supplier_invoice_no', models.CharField(max_length=64, unique=True)),
                ('invoice_date', models.DateField()),
                ('supplier', models.CharField(blank=True, default='', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='Approved', max_length=32)),
                ('payment_status', models.CharField(default='Not Paid', max_length=32)),
                ('sub_total', models.FloatField(default=0)),
                ('tax_total', models.FloatField(default=0)),
                ('net_total', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('balance_amount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'purchase_invoice_entries',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('order_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=64)),
                ('supplier', models.CharField(max_length=128)),
                ('amount', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=32)),
                ('warehouse', models.CharField(blank=True, default='', max_length=128)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(blank=True, default='Draft', max_length=32)),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=64, unique=True)),
                ('payment_date', models.DateField()),
                ('tran_no', models.CharField(blank=True, default='', max_length=64)),
                ('supplier_invoice_no', models.CharField(blank=True, default='', max_length=64)),
                ('supplier', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('mode', models.CharField(default='Cash', max_length=32)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'purchase_payments',
            },
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('unit_price', models.FloatField(default=0)),
                ('tax_percent', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'purchase_products',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=64)),
                ('invoice_date', models.DateField()),
                ('customer', models.CharField(max_length=128)),
                ('total_amount', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'sales_invoices',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64)),
                ('order_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=64)),
                ('customer', models.CharField(max_length=128)),
                ('amount', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
                ('salesman', models.CharField(default='Salesman 1', max_length=64)),
            ],
            options={
                'db_table': 'sales_orders',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_no', models.CharField(max_length=64, unique=True)),
                ('adjustment_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(blank=True, default='Admin', max_length=64)),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'stock_adjustments',
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=64, unique=True)),
                ('request_date', models.DateField()),
                ('from_location', models.CharField(blank=True, default='', max_length=128)),
                ('to_location', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='Pending Approval', max_length=32)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(blank=True, default='Admin', max_length=64)),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'stock_requests',
            },
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_take_no', models.CharField(max_length=64, unique=True)),
                ('stock_take_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='Pending', max_length=32)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('user_name', models.CharField(blank=True, default='Admin', max_length=64)),
                ('last_stock_take_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_takes',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=64, unique=True)),
                ('transfer_date', models.DateField()),
                ('from_location', models.CharField(blank=True, default='', max_length=128)),
                ('to_location', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='Draft', max_length=32)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('has_discrepancy', models.BooleanField(default=False)),
                ('discrepancy_remarks', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'stock_transfers',
            },
        ),
        migrations.CreateModel(
            name='SupplierLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, default='', max_length=128)),
                ('entry_date', models.DateField()),
                ('document_type', models.CharField(default='', max_length=64)),
                ('document_no', models.CharField(default='', max_length=64)),
                ('amount', models.FloatField(default=0)),
                ('dr_cr', models.CharField(default='CR', max_length=8)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'supplier_ledger',
            },
        ),
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('contact', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(blank=True, default='INR', max_length=16)),
                ('payment_terms', models.CharField(blank=True, default='Net 30', max_length=64)),
            ],
            options={
                'db_table': 'supplier_master',
            },
        ),
        migrations.CreateModel(
            name='WarehouseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'warehouse_master',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=32)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('ordered_qty', models.FloatField(default=0)),
                ('received_qty', models.FloatField(default=0)),
                ('accepted_qty', models.FloatField(default=0)),
                ('damaged_qty', models.FloatField(default=0)),
                ('quality_status', models.CharField(default='Pass', max_length=16)),
                ('unit_price', models.FloatField(default=0)),
                ('tax_percent', models.FloatField(default=0)),
                ('line_total', models.FloatField(default=0)),
                ('net_total', models.FloatField(default=0)),
                ('is_over_delivery', models.BooleanField(default=False)),
                ('goods_receipt', models.ForeignKey(db_column='goods_receipt_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.goodsreceipt')),
            ],
            options={
                'db_table': 'goods_receipt_items',
            },
        ),
        migrations.CreateModel(
            name='GoodsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=64, unique=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=128)),
                ('return_date', models.DateField()),
                ('invoice_no', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='Pending Vendor Confirmation', max_length=64)),
                ('total_amount', models.FloatField(default=0)),
                ('original_gr', models.ForeignKey(db_column='original_gr_id', on_delete=django.db.models.deletion.PROTECT, related_name='goods_returns', to='erp_app.goodsreceipt')),
            ],
            options={
                'db_table': 'goods_returns',
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(max_length=64, unique=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=128)),
                ('note_date', models.DateField()),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(default='Open', max_length=32)),
                ('goods_return', models.OneToOneField(db_column='goods_return_id', on_delete=django.db.models.deletion.CASCADE, related_name='debit_note', to='erp_app.goodsreturn')),
            ],
            options={
                'db_table': 'debit_notes',
            },
        ),
        migrations.CreateModel(
            name='GoodsReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=32)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('quantity', models.FloatField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=128)),
                ('condition', models.CharField(default='Damaged', max_length=64)),
                ('unit_price', models.FloatField(default=0)),
                ('tax_percent', models.FloatField(default=0)),
                ('line_total', models.FloatField(default=0)),
                ('net_total', models.FloatField(default=0)),
                ('goods_return', models.ForeignKey(db_column='goods_return_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.goodsreturn')),
                ('source_gr_item', models.ForeignKey(db_column='source_gr_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='erp_app.goodsreceiptitem')),
            ],
            options={
                'db_table': 'goods_return_items',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=32)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('stock_qty', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'inventory',
                'constraints': [models.UniqueConstraint(fields=('product_code', 'location'), name='uniq_inventory_product_location')],
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(db_column='purchase_order_id', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='erp_app.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=32)),
                ('product_name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('tax_percent', models.FloatField(default=0)),
                ('line_total', models.FloatField(default=0)),
                ('net_total', models.FloatField(default=0)),
                ('purchase_order', models.ForeignKey(db_column='purchase_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='erp_app.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=32)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('billed_qty', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('tax_percent', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('net_total', models.FloatField(default=0)),
                ('gr_item', models.ForeignKey(db_column='gr_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='erp_app.goodsreceiptitem')),
                ('invoice_entry', models.ForeignKey(db_column='invoice_entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.purchaseinvoiceentry')),
                ('po_item', models.ForeignKey(blank=True, db_column='po_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='erp_app.purchaseorderitem')),
            ],
            options={
                'db_table': 'purchase_invoice_entry_items',
            },
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='po_item',
            field=models.ForeignKey(blank=True, db_column='po_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='erp_app.purchaseorderitem'),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('amount', models.FloatField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='erp_app.product')),
                ('sales_order', models.ForeignKey(db_column='sales_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.salesorder')),
            ],
            options={
                'db_table': 'sales_order_items',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=32)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('old_qty', models.FloatField(default=0)),
                ('adjustment_sign', models.CharField(default='-', max_length=1)),
                ('adjustment_qty', models.FloatField(default=0)),
                ('new_qty', models.FloatField(default=0)),
                ('reason', models.CharField(default='Manual Correction', max_length=64)),
                ('stock_adjustment', models.ForeignKey(db_column='stock_adjustment_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.stockadjustment')),
            ],
            options={
                'db_table': 'stock_adjustment_items',
            },
        ),
        migrations.CreateModel(
            name='StockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=32)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('carton_qty', models.FloatField(default=0)),
                ('loose_qty', models.FloatField(default=0)),
                ('total_qty', models.FloatField(default=0)),
                ('stock_request', models.ForeignKey(db_column='stock_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.stockrequest')),
            ],
            options={
                'db_table': 'stock_request_items',
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=32)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('system_qty', models.FloatField(default=0)),
                ('physical_qty', models.FloatField(default=0)),
                ('variance', models.FloatField(default=0)),
                ('stock_take', models.ForeignKey(db_column='stock_take_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.stocktake')),
            ],
            options={
                'db_table': 'stock_take_items',
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=32)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('qty', models.FloatField(default=0)),
                ('stock_transfer', models.ForeignKey(db_column='stock_transfer_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.stocktransfer')),
            ],
            options={
                'db_table': 'stock_transfer_items',
            },
        ),
    ]
