# Generated by Django 6.0.2 on 2026-03-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_no', models.CharField(max_length=50)),
                ('tran_date', models.DateField()),
                ('customer_name', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_amount', models.FloatField(default=0)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sales_quotations',
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=150)),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.salesquotation')),
            ],
            options={
                'db_table': 'sales_quotation_items',
            },
        ),
    ]
