# Generated by Django 6.0.2 on 2026-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_salesquotation_salesorder_printed_salesorder_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_no', models.CharField(max_length=50)),
                ('tran_date', models.DateField()),
                ('customer', models.CharField(max_length=150)),
                ('sub_total', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('net_total', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
    ]
