# Generated by Django 6.0.3 on 2026-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0006_supplier_suppliercontact_supplierlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=200, unique=True)),
                ('tax_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_for', models.CharField(default='Both', max_length=50)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sort_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tax_master',
            },
        ),
    ]
