# Generated by Django 6.0.3 on 2026-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0007_taxmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=200, unique=True)),
                ('no_of_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'terms_master',
            },
        ),
    ]
