# Generated by Django 6.0.3 on 2026-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0008_termsmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=20, unique=True)),
                ('currency_name', models.CharField(max_length=200)),
                ('currency_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'currency_master',
            },
        ),
    ]
