# Generated by Django 6.0.3 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0009_currencymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymodeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymode_name', models.CharField(max_length=200, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('payment_type', models.CharField(blank=True, max_length=80)),
                ('show_back_office', models.BooleanField(default=True)),
                ('show_ecommerce', models.BooleanField(default=False)),
                ('need_reference_no', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('locations', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'paymode_master',
            },
        ),
    ]
