from django.urls import path
from .views import login_view, logout_view

from .views import (
    analysis_view,
    sales_analysis_view,
    stock_analysis_view,
    dashboard_view,
    finance_view,
    goods_receipt_view,
    goods_return_view,
    gor_approve_api,
    gor_gr_details_api,
    gor_save_api,
    gr_po_details_api,
    gr_save_api,
    po_add_product_api,
    po_add_supplier_api,
    po_add_warehouse_api,
    po_save_api,
    pi_pay_api,
    pi_gr_details_api,
    pi_save_api,
    sa_save_api,
    sr_save_api,
    st_confirm_api,
    st_save_api,
    stk_finalize_api,
    stk_save_api,
    health_view,
    inventory_view,
    master_view,
    product_view,
    purchase_invoice_view,
    purchase_order_view,
    purchase_view,
    sales_view,
    settings_view,
    stock_view,
    stock_adjustment_view,
    stock_adjustment_new_view,
    stock_request_view,
    stock_request_new_view,
    stock_take_view,
    stock_take_new_view,
    stock_transfer_view,
    stock_transfer_new_view,
    sales_orders_view,
    sales_quotation_view,
    sales_return_view,
    unapproved_orders_view,
    delivery_view,
    invoice_view,
    salesquotation_new_view,
    salesorders_new_view,
    delivery_new_view,  
    salesreturn_new_view,
    invoice_new_view,
)

urlpatterns = [
    path("login/", login_view, name="login"),
    path("", dashboard_view, name="dashboard"),
    path("logout/", logout_view, name="logout"),
    path("inventory/", inventory_view, name="inventory"),
    path("inventory/master/", master_view, name="master"),
    path("inventory/product/", product_view, name="product"),
    path("inventory/purchase/", purchase_view, name="purchase"),
    path("inventory/purchase/order/", purchase_order_view, name="purchase_order"),
    path("inventory/purchase/order/api/add-supplier/", po_add_supplier_api, name="po_add_supplier_api"),
    path("inventory/purchase/order/api/add-warehouse/", po_add_warehouse_api, name="po_add_warehouse_api"),
    path("inventory/purchase/order/api/add-product/", po_add_product_api, name="po_add_product_api"),
    path("inventory/purchase/order/api/save/", po_save_api, name="po_save_api"),
    path("inventory/purchase/goods-receipt/", goods_receipt_view, name="goods_receipt"),
    path("inventory/purchase/goods-receipt/api/po-details/", gr_po_details_api, name="gr_po_details_api"),
    path("inventory/purchase/goods-receipt/api/save/", gr_save_api, name="gr_save_api"),
    path("inventory/purchase/goods-return/", goods_return_view, name="goods_return"),
    path("inventory/purchase/goods-return/api/gr-details/", gor_gr_details_api, name="gor_gr_details_api"),
    path("inventory/purchase/goods-return/api/save/", gor_save_api, name="gor_save_api"),
    path("inventory/purchase/goods-return/api/approve/", gor_approve_api, name="gor_approve_api"),
    path("inventory/purchase/invoice/", purchase_invoice_view, name="purchase_invoice"),
    path("inventory/purchase/purchase-invoice/", purchase_invoice_view),
    path("inventory/purchase/purchase_invoice/", purchase_invoice_view),
    path("inventory/purchase/invoice/api/gr-details/", pi_gr_details_api, name="pi_gr_details_api"),
    path("inventory/purchase/invoice/api/save/", pi_save_api, name="pi_save_api"),
    path("inventory/purchase/invoice/api/pay/", pi_pay_api, name="pi_pay_api"),
    path("inventory/purchase/purchase-invoice/api/gr-details/", pi_gr_details_api),
    path("inventory/purchase/purchase-invoice/api/save/", pi_save_api),
    path("inventory/sales/", sales_view, name="sales"),
    path("inventory/sales-quotation/", sales_quotation_view, name="sales_quotation"),
    path("inventory/unapproved-orders/", unapproved_orders_view, name="unapproved_orders"),
    path("inventory/sales_orders/", sales_orders_view, name="sales_orders"),
    path("inventory/delivery/", delivery_view, name="delivery"),
    path("inventory/sales-return/", sales_return_view, name="sales_return"),
    path("inventory/invoice/", invoice_view, name="invoice"),
    path("sales/salesquotation_new/",salesquotation_new_view,name="salesquotation_new"),
    path("sales/salesorders_new/",salesorders_new_view,name="salesorders_new"),
    path("sales/delivery_new/",delivery_new_view,name="delivery_new"),
    path("sales/salesreturn_new/",salesreturn_new_view,name="salesreturn_new"),
    path("sales/invoice_new/",invoice_new_view,name="invoice_new"),
    path("inventory/stock/", stock_view, name="stock"),
    path("inventory/stock/request/", stock_request_view, name="stock_request"),
    path("inventory/stock/request/new/", stock_request_new_view, name="stock_request_new"),
    path("inventory/stock/request/api/save/", sr_save_api, name="sr_save_api"),
    path("inventory/stock/transfer/", stock_transfer_view, name="stock_transfer"),
    path("inventory/stock/transfer/new/", stock_transfer_new_view, name="stock_transfer_new"),
    path("inventory/stock/transfer/api/save/", st_save_api, name="st_save_api"),
    path("inventory/stock/transfer/api/confirm/", st_confirm_api, name="st_confirm_api"),
    path("inventory/stock/adjustment/", stock_adjustment_view, name="stock_adjustment"),
    path("inventory/stock/adjustment/new/", stock_adjustment_new_view, name="stock_adjustment_new"),
    path("inventory/stock/adjustment/api/save/", sa_save_api, name="sa_save_api"),
    path("inventory/stock/take/", stock_take_view, name="stock_take"),
    path("inventory/stock/take/new/", stock_take_new_view, name="stock_take_new"),
    path("inventory/stock/take/api/save/", stk_save_api, name="stk_save_api"),
    path("inventory/stock/take/api/finalize/", stk_finalize_api, name="stk_finalize_api"),
    path("inventory/analysis/", analysis_view, name="analysis"),
    path('sales-analysis/', sales_analysis_view, name='sales_analysis'),
    path('stock-analysis/', stock_analysis_view, name='stock_analysis'),
    path("finance/", finance_view, name="finance"),
    path("settings/", settings_view, name="settings"),
    path("health/", health_view, name="health"),
]
